BuildIt-Poland/daily-routine

package-lock.json, package.json
Created deployment setup with GitHub Pages, and [gh-pages](https://www.npmjs.com/package/gh-pages) npm package.
=> [DR-17] Deployment Setup

package-lock.json, package.json, src/App.js
[DR-16](https://digitalrig.atlassian.net/browse/DR-16) Configure Prettier and Linter
Developer linting tools configuration
=> [DR-16] Configure Prettier and Linter

.gitignore, package-lock.json, package.json, src/components/App/__tests__/App.test.js, src/components/App/__tests__/__snapshots__/App.test.js.snap, src/components/BackEndRolePage/__tests__/BackEndRolePage.test.js, src/components/BackEndRolePage/__tests__/__snapshots__/BackEndRolePage.test.js.snap, src/components/DevOpsRolePage/__tests__/DevOpsRolePage.test.js, src/components/DevOpsRolePage/__tests__/__snapshots__/DevOpsRolePage.test.js.snap, src/components/FrontEndRolePage/__tests__/FrontEndRolePage.test.js, src/components/FrontEndRolePage/__tests__/__snapshots__/FrontEndRolePage.test.js.snap, src/components/LandingPage/__tests__/LandingPage.test.js, src/components/LandingPage/__tests__/__snapshots__/LandingPage.test.js.snap
[#JIRAID](https://digitalrig.atlassian.net/browse/DR-XX) #Routing setup tests
=> [DR-14] Routing setup tests

.circleci/config.yml, deploy.js, package-lock.json, package.json
[DR-17](https://digitalrig.atlassian.net/browse/DR-17) AWS Deployment setup
=> [DR-17] Deployment script for AWS S3 service

.circleci/config.yml
[FIX] CI/CD Application build fix
=> [FIX] CI/CD Application build fix

src/components/App/App.js, src/components/App/__tests__/__snapshots__/App.test.js.snap, src/components/LandingPage/LandingPage.js, src/styles/__tests__/generateTheme.test.js, src/styles/generateTheme.js
[DR-73](https://digitalrig.atlassian.net/browse/DR-73) Theming for Role Pages
Set proper colour theme for different Role pages, root path, and unknown routes.
=> [DR-73] Theming for Role Pages

README.md
[DR-7](https://digitalrig.atlassian.net/browse/DR-7) Readme with useful links
Updated readme with all relevant information.
=> [DR-7] Readme with useful links

src/components/Icons/Cross.js, src/components/Icons/__tests__/Cross.test.js, src/components/Icons/__tests__/__snapshots__/Cross.test.js.snap, src/components/Icons/index.js
[DR-75](https://digitalrig.atlassian.net/browse/DR-75) Close icon
Added close cross icon.
=> [DR-75] Close icon

.circleci/config.yml, Dockerfile
[FIX] Docker file + circleci update
Adding dockerfile + remove redundant steps
=> Docker file + remove redundant setup

package.json
Fixed test coverage script, so it runs correctly.
=> [FIX] Test coverage script

.gitignore, cypress/integration/App.test.js, cypress/integration/BackEndRolePage.test.js, cypress/integration/DevOpsRolePage.test.js, cypress/integration/Footer.test.js, cypress/integration/FrontEndRolePage.test.js, cypress/integration/Logo.test.js, cypress/support/commands.js, cypress/support/index.js, src/components/ActionButtons/ActionButtons.js, src/components/ActionButtons/BragButton.js, src/components/ActionButtons/ConfessButton.js, src/components/AppBar/Logo.js, src/components/AppBar/__tests__/__snapshots__/Logo.test.js.snap, src/components/BackEndRolePage/BackEndRolePage.js, src/components/DevOpsRolePage/DevOpsRolePage.js, src/components/Footer/Footer.js, src/components/FrontEndRolePage/FrontEndRolePage.js, src/components/RoleBar/__tests__/RoleBar.test.js, src/components/RoleBar/__tests__/__snapshots__/RoleBar.test.js.snap, src/components/RoleButtons/RoleButtons.js, src/constants/roles.js
=> [DR-77] e2e tests for navigation between routes

src/components/GenderSettings/Input.js, src/components/GenderSettings/Label.js
[FIX] #Gender settings text position
=> [FIX] Gender settings text position

package-lock.json, package.json, src/constants/genders.js, src/context/GenderContext.js, src/hooks/__tests__/useLocalStorage.test.js, src/hooks/useLocalStorage.js, src/setupTests.js
[#JIRAID](https://digitalrig.atlassian.net/browse/DR-49) #LocalStorage for gender
=> [DR-49] LocaStorage for gender

package.json, src/components/App/App.js, src/components/GenderSettings/RadioButton.js, src/components/SidePanel/SidePanel.js
=> [FIX] PropTypes eslint rule

src/components/SettingsPanel/SettingsPanel.js, src/components/SidePanel/Overlay.js, src/components/SidePanel/SidePanel.js
[#JIRAID](https://digitalrig.atlassian.net/browse/DR-XX) #Close settings panel when click overlay
=> [DR-90] Close settings panel when click overlay

src/components/SettingsTrigger/SettingsTrigger.js
=> [FIX] Close settings panel

src/components/ActionButtons/BragButton.js, src/components/ActionButtons/ConfessButton.js
[#JIRAID](https://digitalrig.atlassian.net/browse/DR-92) 
#Action buttons dynamic text
=> [DR-92] Action buttons dynamic text

.github/pull_request_template.md, package-lock.json, package.json, src/components/ActionButtons/LightbulbIcon.js, src/components/ActionButtons/SaltGrinderIcon.js, src/components/ActionButtons/__tests__/__snapshots__/LightbulbIcon.test.js.snap, src/components/ActionButtons/__tests__/__snapshots__/SaltGrinderIcon.test.js.snap, src/components/BackEndRolePage/BackEndBrag.js, src/components/BackEndRolePage/BackEndConfess.js, src/components/DevOpsRolePage/DevOpsBrag.js, src/components/DevOpsRolePage/DevOpsConfess.js, src/components/FrontEndRolePage/FrontEndBrag.js, src/components/FrontEndRolePage/FrontEndConfess.js, src/hooks/__tests__/useLocalStorage.test.js, src/quotes/backEndQuotes.js, src/quotes/devOpsQuotes.js, src/quotes/frontEndQuotes.js
[DR-41](https://digitalrig.atlassian.net/browse/DR-41) List of messages for each character
[DevOps] 123
```
Yesterday I was implementing PUT method for missing RESTful API endpoint.
```
- Every repository contributor can vote with :thumbsup: or :thumbsdown: for role quotes
- Quote pull request needs to have at lest 51% of :thumbsup: votes before merge
- Pull Request will be approved after successful voting :white_check_mark:
=> [DR-41] List of messages for each character

src/components/ActionButtons/__tests__/BragButton.test.js, src/components/ActionButtons/__tests__/ConfessButton.test.js, src/index.js
[#JIRAID](https://digitalrig.atlassian.net/browse/DR-85) Service worker for prod
=> [DR-85] Service worker for prod

cypress.json
[FIX] Error cross-origin frame
=> [FIX] Error cross-origin frame

src/components/ActionButtons/ActionButtons.js, src/components/ActionButtons/BragButton.js, src/components/ActionButtons/ConfessButton.js, src/components/ActionButtons/__tests__/ActionButtons.test.js, src/components/ActionButtons/__tests__/BragButton.test.js, src/components/ActionButtons/__tests__/ConfessButton.test.js, src/components/BackEndRolePage/BackEndBrag.js, src/components/BackEndRolePage/BackEndConfess.js, src/components/BackEndRolePage/BackEndRolePage.js, src/components/BackEndRolePage/__tests__/__snapshots__/BackEndRolePage.test.js.snap, src/components/DevOpsRolePage/DevOpsBrag.js, src/components/DevOpsRolePage/DevOpsConfess.js, src/components/DevOpsRolePage/DevOpsRolePage.js, src/components/DevOpsRolePage/__tests__/__snapshots__/DevOpsRolePage.test.js.snap, src/components/FrontEndRolePage/FrontEndBrag.js, src/components/FrontEndRolePage/FrontEndConfess.js, src/components/FrontEndRolePage/FrontEndRolePage.js, src/components/QuoteBubble/QuoteBubble.js, src/components/QuoteBubble/__tests__/QuoteBubble.test.js, src/components/QuoteBubble/__tests__/__snapshots__/QuoteBubble.test.js.snap, src/components/QuoteBubble/index.js, src/quotes/backEndQuotes.js, src/quotes/devOpsQuotes.js, src/quotes/frontEndQuotes.js, src/types/index.js, src/utils/extractActionFromPath.js, src/utils/extractQuoteIDFromPath.js, src/utils/quotesService.js
This is [WIP] PR. Please check it before I will proceed to fixing the tests.
[DR-59](https://digitalrig.atlassian.net/browse/DR-59) The E.N.G.I.N.E
Use Quotes files as a source of quotes per role, based on given URL
=> [WIP][DR-59] The E.N.G.I.N.E

cypress/integration/BackEndRolePage.test.js, cypress/integration/DevOpsRolePage.test.js, cypress/integration/FrontEndRolePage.test.js
Hotfix for broken e2e tests after #73 merge.
=> [FIX] e2e tests

public/index.html
[DR-101](https://digitalrig.atlassian.net/browse/DR-101) Adds meta tags for Open Graph API
=> [DR-101] Adds meta tags for Open Graph API

package.json, src/components/QuoteBubble/QuoteBubble.js
PR template for features/fixes:
Updated PR based on closed PR https://github.com/BuildIt-Poland/daily-routine/pull/86. 
Removed all CSS changes and left only trim Quote function
=> [DR-105] Calculated QuoteBubble wrapper height

cypress/integration/QuoteBubble.test.js, package-lock.json
Attempt to fix e2e for quote bubble.
=> [FIX] Quote bubble e2e

cypress/integration/QuoteBubble.test.js
=> [FIX] QuoteBubble e2e v2

src/components/Character/Character.js, src/components/Error/Error.js, src/components/Error/Wrapper.js, src/components/Error/__tests__/Error.test.js, src/components/Error/__tests__/Wrapper.test.js, src/components/Error/__tests__/__snapshots__/Wrapper.test.js.snap, src/components/Error/index.js, src/components/ErrorBoundary/ErrorBoundary.js, src/components/ErrorBoundary/__tests__/ErrorBoundary.test.js, src/components/ErrorBoundary/__tests__/__snapshots__/ErrorBoundary.test.js.snap, src/components/ErrorBoundary/index.js, src/components/LandingPage/LandingPage.js, src/components/QuoteBubble/QuoteBubble.js, src/components/SettingsPanel/SettingsPanel.js, src/styles/designTokens.js
Create ErrorBoundary component displaying error message (eg.: 'Oops, something went wrong...'). Error message should have white background with rounded corners.
Figure out critical components which should be wrapped by it besides whole App
=> [DR-112] ErrorBoundary component

src/quotes/generate.js, src/quotes/quotes.js, src/utils/__tests__/quotesService.test.js
PR template for features/fixes:
**# [JIRAID / FIX](https://digitalrig.atlassian.net/browse/DR-103)  Fix malformed roles/actions/quoteids**
As in topic
=> [FIX] Malformed quoteIDs

src/quotes/quotes.js
=> [FIX] small quote tweaks

src/context/__tests__/QuoteContext.test.js
=> [FIX] Missing QuoteContext test cases

src/components/Characters/Robot/GenderFlower.js, src/components/Characters/Robot/__tests__/__snapshots__/GenderFlower.test.js.snap
[FIX] Robot gender flower position
=> [FIX] Robot gender flower position

package-lock.json, package.json, src/quotes/encode.js, src/quotes/generate.js, src/quotes/quotes.js, src/utils/__tests__/quotesService.test.js
Fixing issues that appear due to "remainder" modulo implementation in js.
Adding malformed actions support.
=> [DR-122] Fixing issues with modulo + malformed urls

cypress/integration/PageNotFound.test.js, src/components/QuoteBubble/QuoteBubble.js, src/components/QuoteBubble/__tests__/__snapshots__/QuoteBubble.test.js.snap
PR template for features/fixes:
=> [DR -115] Message not found e2e tests

src/components/ActionButtons/LightbulbIcon.js, src/components/ActionButtons/SaltGrinderIcon.js, src/components/ActionButtons/__tests__/__snapshots__/LightbulbIcon.test.js.snap, src/components/ActionButtons/__tests__/__snapshots__/SaltGrinderIcon.test.js.snap, src/components/App/Wrapper.js, src/components/App/__tests__/__snapshots__/App.test.js.snap, src/components/Characters/SugarCat/SugarCubeLegs.js, src/components/Characters/SugarCat/__tests__/__snapshots__/SugarCubeLegs.test.js.snap, src/components/GenderSettings/Input.js, src/components/QuoteBubble/Bubble.js, src/components/QuoteBubble/BubbleTail.js, src/components/QuoteBubble/__tests__/__snapshots__/Bubble.test.js.snap, src/components/QuoteBubble/__tests__/__snapshots__/BubbleTail.test.js.snap, src/components/QuoteBubble/__tests__/__snapshots__/QuoteBubble.test.js.snap, src/components/RedirectButton/ArrowIcon.js, src/components/RedirectButton/__tests__/__snapshots__/ArrowIcon.test.js.snap, src/components/RedirectButton/__tests__/__snapshots__/RedirectButton.test.js.snap, src/components/RoleButtons/__tests__/__snapshots__/BackEndButton.test.js.snap, src/components/RoleButtons/__tests__/__snapshots__/DevOpsButton.test.js.snap, src/components/RoleButtons/__tests__/__snapshots__/FrontEndButton.test.js.snap
=> [DR-124] Z-index ordering 

src/components/ActionButtons/ActionButtons.js, src/components/App/App.js, src/components/BackEndRolePage/BackEndRolePage.js, src/components/DevOpsRolePage/DevOpsRolePage.js, src/components/Error/Wrapper.js, src/components/Error/__tests__/__snapshots__/Wrapper.test.js.snap, src/components/ErrorBoundary/__tests__/__snapshots__/ErrorBoundary.test.js.snap, src/components/FrontEndRolePage/FrontEndRolePage.js, src/components/PageNotFound/PageNotFound.js, src/components/RoleButtons/RoleButtons.js, src/components/RouteTransitionAnimation/AnimatedOverlay.js, src/components/RouteTransitionAnimation/RouteTransitionAnimation.js, src/components/RouteTransitionAnimation/__tests__/__snapshots__/RouteTransitionAnimation.test.js.snap, src/components/SettingsPanel/SettingsPanel.js, src/context/RouteTransitionAnimationContext.js, src/hooks/__tests__/useLockBodyScroll.test.js, src/hooks/useLockBodyScroll.js
=> [DR-118] Polish transition animation

src/components/GenderSettings/Label.js
Little improvement; added _user-select: none_ to GenderSettings Label.
=> [FIX] Add missing user-select

src/hooks/__tests__/useLockBodyScroll.test.js, src/hooks/useLockBodyScroll.js, src/quotes/encode.js, src/quotes/generate.js, src/quotes/nicknameParts.js
To hide scrollbar in some circumstances updated _overflow_ from _scroll_ to _auto_.
=> [FIX] Overflow auto

.github/pull_request_template.md, README.md
Streamlined readme a bit. Updated PR template to be in sync with readme.
=> [FIX] Update PR template and readme

extras/daily-routine-proto-personas.pdf, package-lock.json, package.json
=> [FIX] Dependencies cleanup and extras added
